#!/usr/bin/env bash

WALLDIR="$HOME/Pictures/wallpapers"
CONF="$HOME/.config/hypr/hyprpaper.conf"
LAST_WALL="$HOME/.config/hypr/last_wallpaper.txt"

mkdir -p "$(dirname "$CONF")"

WALL=$(find "$WALLDIR" -type f \( -iname '*.jpg' -o -iname '*.png' \) 2>/dev/null | shuf -n 1)

if [[ -z "$WALL" ]]; then
  echo "❌ No wallpapers found in $WALLDIR"
  exit 1
fi

# Avoid repeating same wallpaper twice in a row
if [[ -f "$LAST_WALL" ]]; then
  while [[ "$WALL" == "$(cat "$LAST_WALL" 2>/dev/null)" ]]; do
    WALL=$(find "$WALLDIR" -type f \( -iname '*.jpg' -o -iname '*.png' \) 2>/dev/null | shuf -n 1)
  done
fi

# Absolute path for hyprctl
[[ "$WALL" != /* ]] && WALL="$(cd "$(dirname "$WALL")" 2>/dev/null && pwd)/$(basename "$WALL")"

echo "$WALL" > "$LAST_WALL"

echo "# Autogenerated hyprpaper config" > "$CONF"
echo "preload = $WALL" >> "$CONF"
for MON in $(hyprctl monitors 2>/dev/null | awk '/^Monitor/ {gsub(/:$/,"",$2); print $2}'); do
  echo "wallpaper = $MON,$WALL" >> "$CONF"
done

# Apply via IPC if hyprland is up; otherwise start hyprpaper with config
if command -v hyprctl &>/dev/null && hyprctl hyprpaper listloaded &>/dev/null; then
  hyprctl hyprpaper preload "$WALL" 2>/dev/null || true
  for MON in $(hyprctl monitors 2>/dev/null | awk '/^Monitor/ {gsub(/:$/,"",$2); print $2}'); do
    hyprctl hyprpaper wallpaper "$MON,$WALL" 2>/dev/null || true
  done
else
  pkill -x hyprpaper 2>/dev/null || true
  sleep 0.5
  hyprpaper -c "$CONF" &
fi
