#!/usr/bin/env bash
# Writes hyprpaper config only. hyprland.conf starts hyprpaper after this.

WALLDIR="$HOME/Pictures/wallpapers"
CONF="$HOME/.config/hypr/hyprpaper.conf"
LAST_WALL="$HOME/.config/hypr/last_wallpaper.txt"

mkdir -p "$(dirname "$CONF")"

WALL=$(find "$WALLDIR" -type f \( -iname '*.jpg' -o -iname '*.png' \) 2>/dev/null | shuf -n 1)

if [[ -z "$WALL" ]]; then
  echo "❌ No wallpapers found in $WALLDIR" >&2
  exit 1
fi

# Avoid repeating same wallpaper twice in a row
if [[ -f "$LAST_WALL" ]]; then
  while [[ "$WALL" == "$(cat "$LAST_WALL" 2>/dev/null)" ]]; do
    WALL=$(find "$WALLDIR" -type f \( -iname '*.jpg' -o -iname '*.png' \) 2>/dev/null | shuf -n 1)
  done
fi

[[ "$WALL" != /* ]] && WALL="$(cd "$(dirname "$WALL")" 2>/dev/null && pwd)/$(basename "$WALL")"
echo "$WALL" > "$LAST_WALL"

# hyprpaper format: preload = path ; wallpaper = monitor, path (space after comma per wiki)
echo "# Autogenerated hyprpaper config" > "$CONF"
echo "preload = $WALL" >> "$CONF"

# Get monitor names (jq preferred; awk fallback strips trailing colon from "HDMI-A-1:")
get_monitors() {
  if command -v jq &>/dev/null; then
    hyprctl -j monitors | jq -r '.[].name'
  else
    hyprctl monitors | awk '/Monitor/ {gsub(/:$/, "", $2); print $2}'
  fi
}
for MON in $(get_monitors); do
  echo "Writing wallpaper for monitor $MON"
  echo "wallpaper = $MON,$WALL" >> "$CONF"
done
