#!/usr/bin/env bash
# Set wallpaper: write hyprpaper config and restart hyprpaper.
# Usage: ./set-wallpaper.sh [/path/to/wallpaper.jpg]

CONF="$HOME/.config/hypr/hyprpaper.conf"
LAST_WALL="$HOME/.config/hypr/last_wallpaper.txt"
WALLDIR="$HOME/Pictures/wallpapers"

if [[ -z "$1" ]]; then
    WALLPAPER=$(find "$WALLDIR" -type f \( -iname '*.jpg' -o -iname '*.png' \) 2>/dev/null | shuf -n 1)
    if [[ -z "$WALLPAPER" ]]; then
        echo "❌ No wallpapers found in $WALLDIR" >&2
        exit 1
    fi
else
    WALLPAPER="$1"
fi

[[ "$WALLPAPER" != /* ]] && WALLPAPER="$(cd "$(dirname "$WALLPAPER")" 2>/dev/null && pwd)/$(basename "$WALLPAPER")"
if [[ ! -f "$WALLPAPER" ]]; then
    echo "❌ Wallpaper not found: $WALLPAPER" >&2
    exit 1
fi

mkdir -p "$(dirname "$CONF")"
echo "$WALLPAPER" > "$LAST_WALL"

# Get active monitors using hyprctl
get_monitors() {
  if command -v jq &>/dev/null; then
    hyprctl -j monitors | jq -r '.[].name'
  else
    hyprctl monitors | awk '/Monitor/ {gsub(/:$/, "", $2); print $2}'
  fi
}

# Generate the correct flat-syntax config file
{
  echo "# Autogenerated hyprpaper config"
  echo "preload = $WALLPAPER"
  echo ""

  MONS=($(get_monitors))
  if [[ ${#MONS[@]} -gt 0 ]]; then
    for MON in "${MONS[@]}"; do
      echo "wallpaper = $MON,$WALLPAPER"
    done
  else
    # Fallback to apply to any/all connected monitors if get_monitors returned empty
    echo "wallpaper = ,$WALLPAPER"
  fi
} > "$CONF"

# Kill existing hyprpaper and restart with new config
pkill -x hyprpaper 2>/dev/null || true
hyprpaper &

echo "✅ Wallpaper set to: $WALLPAPER"
