#!/usr/bin/env bash
# Set wallpaper: write hyprpaper config and restart hyprpaper.
# Usage: ./set-wallpaper.sh [/path/to/wallpaper.jpg]

CONF="$HOME/.config/hypr/hyprpaper.conf"
LAST_WALL="$HOME/.config/hypr/last_wallpaper.txt"
WALLDIR="$HOME/Pictures/wallpapers"

if [[ -z "$1" ]]; then
    WALLPAPER=$(find "$WALLDIR" -type f \( -iname '*.jpg' -o -iname '*.png' \) 2>/dev/null | shuf -n 1)
    if [[ -z "$WALLPAPER" ]]; then
        echo "❌ No wallpapers found in $WALLDIR" >&2
        exit 1
    fi
else
    WALLPAPER="$1"
fi

[[ "$WALLPAPER" != /* ]] && WALLPAPER="$(cd "$(dirname "$WALLPAPER")" 2>/dev/null && pwd)/$(basename "$WALLPAPER")"
if [[ ! -f "$WALLPAPER" ]]; then
    echo "❌ Wallpaper not found: $WALLPAPER" >&2
    exit 1
fi

mkdir -p "$(dirname "$CONF")"
echo "$WALLPAPER" > "$LAST_WALL"

# hyprpaper format: preload = path ; wallpaper = monitor, path (space after comma per wiki)
echo "# Autogenerated hyprpaper config" > "$CONF"
echo "preload = $WALLPAPER" >> "$CONF"

# Get monitor names (jq preferred; awk fallback strips trailing colon from "HDMI-A-1:")
get_monitors() {
  if command -v jq &>/dev/null; then
    hyprctl -j monitors | jq -r '.[].name'
  else
    hyprctl monitors | awk '/Monitor/ {gsub(/:$/, "", $2); print $2}'
  fi
}

for MON in $(get_monitors); do
  echo "Setting wallpaper for monitor $MON"
  echo "wallpaper = $MON,$WALLPAPER" >> "$CONF"
done

# Kill existing hyprpaper and restart with new config (IPC broken in some Hyprland versions)
pkill -x hyprpaper 2>/dev/null || true
hyprpaper &

echo "✅ Wallpaper set to: $WALLPAPER"
