#!/usr/bin/env bash
# Set wallpaper: write hyprpaper config and restart hyprpaper.
# Usage: ./set-wallpaper.sh [/path/to/wallpaper.jpg]

CONF="$HOME/.config/hypr/hyprpaper.conf"
LAST_WALL="$HOME/.config/hypr/last_wallpaper.txt"
WALLDIR="$HOME/Pictures/wallpapers"

if [[ -z "$1" ]]; then
    WALLPAPER=$(find "$WALLDIR" -type f \( -iname '*.jpg' -o -iname '*.png' \) 2>/dev/null | shuf -n 1)
    if [[ -z "$WALLPAPER" ]]; then
        echo "❌ No wallpapers found in $WALLDIR" >&2
        exit 1
    fi
else
    WALLPAPER="$1"
fi

[[ "$WALLPAPER" != /* ]] && WALLPAPER="$(cd "$(dirname "$WALLPAPER")" 2>/dev/null && pwd)/$(basename "$WALLPAPER")"
if [[ ! -f "$WALLPAPER" ]]; then
    echo "❌ Wallpaper not found: $WALLPAPER" >&2
    exit 1
fi

mkdir -p "$(dirname "$CONF")"
echo "$WALLPAPER" > "$LAST_WALL"

# hyprpaper format: wallpaper { monitor = X; path = Y } (new block syntax, preload deprecated)
get_monitors() {
  if command -v jq &>/dev/null; then
    hyprctl -j monitors | jq -r '.[].name'
  else
    hyprctl monitors | awk '/Monitor/ {gsub(/:$/, "", $2); print $2}'
  fi
}

{
  echo "# Autogenerated hyprpaper config"
  MONS=($(get_monitors))
  if [[ ${#MONS[@]} -gt 0 ]]; then
    for MON in "${MONS[@]}"; do
      echo "wallpaper {"
      echo "    monitor = $MON"
      echo "    path = $WALLPAPER"
      echo "    fit_mode = cover"
      echo "}"
    done
  else
    echo "wallpaper {"
    echo "    monitor ="
    echo "    path = $WALLPAPER"
    echo "    fit_mode = cover"
    echo "}"
  fi
} > "$CONF"

# Apply wallpaper live via hyprctl if hyprpaper is running
if pgrep -x hyprpaper >/dev/null; then
    echo "Applying live via hyprctl..."
    # Preload the new wallpaper
    hyprctl hyprpaper preload "$WALLPAPER"
    
    # Apply to all monitors individually (empty string is sometimes buggy in newer hyprpaper)
    MONS=($(get_monitors))
    for MON in "${MONS[@]}"; do
        hyprctl hyprpaper wallpaper "$MON,$WALLPAPER"
    done
    
    # Cleanup: unload everything EXCEPT the current wallpaper to save RAM
    # We use 'unload all' but since $WALLPAPER is active, it should stay preloaded
    hyprctl hyprpaper unload all
else
    # Not running, just start it (it will read the newly written $CONF)
    hyprpaper &
fi

echo "✅ Wallpaper set to: $WALLPAPER"
