#!/usr/bin/env bash

WALLDIR="$HOME/Pictures/wallpapers"
CONF="$HOME/.config/hypr/hyprpaper.conf"

mkdir -p "$(dirname "$CONF")"

# Pick one random wallpaper
WALL=$(find "$WALLDIR" -type f \( -iname '*.jpg' -o -iname '*.png' \) | shuf -n 1)

if [[ -z "$WALL" ]]; then
  echo "❌ No wallpapers found in $WALLDIR"
  exit 1
fi

echo "# Autogenerated hyprpaper config" > "$CONF"
echo "preload = $WALL" >> "$CONF"

for MON in $(hyprctl monitors | awk '/Monitor/ {print $2}'); do
  echo "Writing wallpaper for monitor $MON"
  echo "wallpaper = $MON,$WALL" >> "$CONF"
done
