name: NixOS CI main workflow

on:
  push:
    branches: ['**']
  pull_request:
    branches: ['**']
    
# This ensures only one workflow per branch runs at a time
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check-nix:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Nix
        uses: cachix/install-nix-action@v25
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: |
            experimental-features = nix-command flakes

      - name: Prepare test environment
        run: |
          # Create simplified dummy files for testing
          echo '{ config, lib, pkgs, modulesPath, ... }: { }' > hardware-configuration.nix
          echo '{ config, lib, pkgs, ... }: {}' > nvidia-configuration.nix
          mkdir -p modules # Ensure modules directory exists
          
          echo "Modified configuration.nix for testing..."
          cat configuration.nix
      
      - name: Check Nix files syntax
        run: |
          echo "Checking Nix syntax..."
          find . -name "*.nix" -type f -exec nix-instantiate --parse {} \; || true
          
      - name: Check Nix expression evaluation
        run: |
          echo "Evaluating configuration.nix..."
          nix-instantiate --expr "let pkgs = import <nixpkgs> {}; in pkgs.lib.nixosSystem { modules = [ ./configuration.nix ]; }" --dry-run || true