name: NixOS System Configuration CI

on:
  workflow_call:
    secrets:
      inherit: true

jobs:
  check-nix:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v25
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: |
            experimental-features = nix-command flakes

      - name: Prepare test environment
        run: |
          cd nixmod-system
          # Create simplified dummy files for testing
          echo '{ config, lib, pkgs, modulesPath, ... }: { }' > hardware-configuration.nix
          echo '{ config, lib, pkgs, ... }: {}' > nvidia-configuration.nix
          mkdir -p modules # Ensure modules directory exists
          
          echo "Modified configuration.nix for testing..."
          cat configuration.nix
      
      - name: Check Nix files syntax
        run: |
          cd nixmod-system
          echo "Checking Nix syntax..."
          find . -name "*.nix" -type f -exec nix-instantiate --parse {} \; || true
          
      - name: Check Nix expression evaluation
        run: |
          cd nixmod-system
          echo "Evaluating configuration.nix..."
          nix-instantiate --expr "let pkgs = import <nixpkgs> {}; in pkgs.lib.nixosSystem { modules = [ ./configuration.nix ]; }" --dry-run || true

  check-flake:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v25
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: |
            experimental-features = nix-command flakes

      - name: Check flake
        run: |
          cd nixmod-system
          echo "Checking flake.nix..."
          nix flake check --no-build || true

      - name: Show flake info
        run: |
          cd nixmod-system
          echo "Flake info:"
          nix flake info || true

  test-toolkit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v25
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: |
            experimental-features = nix-command flakes

      - name: Test toolkit scripts
        run: |
          echo "Testing toolkit scripts..."
          chmod +x toolkit/*.sh
          
          # Test help commands
          ./toolkit/nixmod.sh help || true
          ./toolkit/helper.sh help || true
          
          echo "Toolkit scripts are executable and show help correctly"
